/**
 * AUTO-GENERATED by scripts/fetch-store-ratings.mjs (runs on prebuild).
 *
 * Do not hand-edit — but DO keep it committed. It serves two jobs:
 *   1. the build-time schema.org AggregateRating (client-side JSON-LD is not
 *      reliably indexed, so those numbers have to be in the HTML), and
 *   2. the fallback shown before — or instead of — the live API response.
 *
 * Source of truth at runtime: GET /api/v1/StoreRatings on the BDT API.
 */
export const generatedStoreRatings = {
  apple: { rating: 4.61, ratingCount: 66 },
  google: { rating: 4.11, ratingCount: 78 },
  combined: { rating: 4.34, ratingCount: 144 },
  fetchedAt: "2026-08-24",
} as const;
