/**
 * AUTO-GENERATED by scripts/fetch-store-ratings.mjs (runs on prebuild).
 *
 * Do not hand-edit, but do keep it committed. It serves two jobs:
 *   1. the build-time schema.org AggregateRating (client-side JSON-LD is not
 *      reliably indexed, so those numbers have to be in the HTML), and
 *   2. the fallback shown before the live API response arrives, or instead
 *      of it if the API is down.
 *
 * Source of truth at runtime: GET /api/v1/StoreRatings on the BDT API.
 */
export const generatedStoreRatings = {
  apple: { rating: 4.63, ratingCount: 70 },
  google: { rating: 4.11, ratingCount: 80 },
  combined: { rating: 4.35, ratingCount: 150 },
  app: { version: "3.0.4", updated: "2026-08-27" },
  fetchedAt: "2026-09-05",
} as const;
